version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging into ECR Container registry $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Starting docker image build for image $IMAGE_REPO_NAME:$IMAGE_TAG.$CODEBUILD_BUILD_NUMBER      
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG.$CODEBUILD_BUILD_NUMBER  .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG.$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG.$CODEBUILD_BUILD_NUMBER      
  post_build:
    commands:
      - echo Completed build of $IMAGE_REPO_NAME:$IMAGE_TAG.$CODEBUILD_BUILD_NUMBER  
      - echo Pushing the Docker image to $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG.$CODEBUILD_BUILD_NUMBER 
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG.$CODEBUILD_BUILD_NUMBER 