apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  DB_NAME: "mypostgresdb"
  DB_USERNAME: "mypostgresuser"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: default
type: Opaque
data:
  DB_PASSWORD: "bXlwb3N0Z3Jlc3Bhc3N3b3Jk"
